### ISSUE TITLE
Document recent changes to U32 Table

### ISSUE THREAD

**Issue by jan-ferdinand** [TritonVM/triton-vm#32]
Document the following changes to the U32 Table:
- [x] include current instruction `ci` (see #16)
- [x] merge the 5 Permutation Arguments into 1 (see #16)
- [x] assert u32-ness of operands by counting rows, introducing 2 columns (see #22)
